# Generated by Django 4.2.1 on 2023-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False)),
                ('depname', models.CharField(db_column='Depname', max_length=45)),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('idgrades', models.AutoField(db_column='idGrades', primary_key=True, serialize=False)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('gpa1', models.FloatField(blank=True, null=True)),
                ('gpa2', models.FloatField(blank=True, null=True)),
                ('gpa3', models.FloatField(blank=True, null=True)),
                ('gpa4', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
    ]
