# Generated by Django 4.2.1 on 2023-06-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': True},
        ),
    ]
