# Generated by Django 4.2.1 on 2023-06-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0003_alter_department_options_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
