# Generated by Django 4.2.1 on 2023-06-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0004_alter_department_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('s', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentmanagementsystem.student')),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coursedetails',
                'managed': False,
            },
        ),
    ]
