# Generated by Django 4.2.1 on 2023-06-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0005_course_coursedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, db_column='Venue', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Examination',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('s', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='studentmanagementsystem.student')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Fees',
                'managed': False,
            },
        ),
    ]
