# Generated by Django 4.2.1 on 2023-06-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0006_examination_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'Teacher',
                'managed': False,
            },
        ),
    ]
