# Generated by Django 4.2.1 on 2023-06-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0007_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salaryid', models.IntegerField(primary_key=True, serialize=False)),
                ('months', models.CharField(blank=True, db_column='Months', max_length=45, null=True)),
                ('ammount', models.IntegerField(blank=True, db_column='Ammount', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Salary',
                'managed': False,
            },
        ),
    ]
